### ISSUE TITLE
WebsocketSubprovider return TypeError: end is not a function

### ISSUE THREAD

**Issue by itoonx** [MetaMask/web3-provider-engine#238]
Version: 14.0.5

This is my code 

```
web3.eth.filter("pending").watch((error, result) => {
        if (!error) {
          console.log(result);
        } else {
          console.log(error);
        }
      }
    )
```

Error
```
TypeError: end is not a function
    at WebsocketSubprovider._handleSocketMessage (/Users/theg0d/Desktop/Works/etherPayment/node_modules/web3-provider-engine/subproviders/websocket.js:120:5)
    at WebSocket.onMessage (/Users/theg0d/Desktop/Works/etherPayment/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver.receiverOnMessage (/Users/theg0d/Desktop/Works/etherPayment/node_modules/ws/lib/websocket.js:718:20)
    at emitOne (events.js:115:13)
    at Receiver.emit (events.js:210:7)
    at Receiver.dataMessage (/Users/theg0d/Desktop/Works/etherPayment/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/Users/theg0d/Desktop/Works/etherPayment/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/Users/theg0d/Desktop/Works/etherPayment/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/Users/theg0d/Desktop/Works/etherPayment/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Receiver.Writable.write (_stream_writable.js:290:11)
    at TLSSocket.socketOnData (/Users/theg0d/Desktop/Works/etherPayment/node_modules/ws/lib/websocket.js:788:35)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at TLSSocket.Readable.push (_stream_readable.js:211:10)
    at TLSWrap.onread (net.js:585:20)
```

**Comment by kumavis** [comment]
@itoonx can you show where you configured provider-engine

**Comment by kumavis** [comment]
is this web3 1.0 or earlier?

**Comment by justinchou** [comment]
@itoonx I'm facing the same error.

**Comment by kumavis** [comment]
it was fixed here https://github.com/MetaMask/web3-provider-engine/pull/281
