### ISSUE TITLE
Latest block tracker should handle null blocks

### ISSUE THREAD

**Issue by ErikMikkelson** [MetaMask/web3-provider-engine#313]
When we poll for latest blocks, the number that we get can sometimes result in a null block when requested.  We only look for an error (there isn't one, because null is a potential valid result) and then line 57 fails (with "Uncaught TypeError: Cannot read property 'number' of null") because we're trying to build a buffer block from a null block object

The code should detect a null block and return, with nothing to do.  We can wait for the next poll to succeed.

**Comment by thegostep** [comment]
running into this issue too

**Comment by theAlexPatin** [comment]
Also have this issue

**Comment by david-hex** [comment]
i believe this is the culprit that is crashing my app

**Comment by felixwatts** [comment]
me too

**Comment by patitonar** [comment]
I also have this issue
```
TypeError: Cannot read property 'number' of null
    at toBufferBlock (node_modules/web3-provider-engine/index.js:212:50)
    at self._getBlockByNumber (node_modules/web3-provider-engine/index.js:57:27)
    at _handleAsync (node_modules/web3-provider-engine/index.js:133:12)
    at node_modules/web3-provider-engine/index.js:192:9
    at node_modules/web3-provider-engine/node_modules/async/internal/once.js:12:16
    at replenish (node_modules/web3-provider-engine/node_modules/async/internal/eachOfLimit.js:61:25)
    at node_modules/web3-provider-engine/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (node_modules/web3-provider-engine/node_modules/async/eachLimit.js:43:36)
    at node_modules/web3-provider-engine/node_modules/async/internal/doLimit.js:9:16
    at end (node_modules/web3-provider-engine/index.js:169:5)
    at node_modules/@0x/subproviders/src/subproviders/ganache.ts:33:13
    at process.nextTick (node_modules/ganache-core/lib/provider.js:114:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by PierBusDev** [comment]
Got the same issue as above recently, doesn't matter the combination of versions of web3 - web3-provider-engine I use
